[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.install]
cmds = ["npm install", "python3 -m pip install -r server/requirements.txt"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "python3 server/app.py"