[phases.setup]
nixPkgs = ["python311", "pip", "nodejs_20"]

[phases.build]
cmds = ["npm install", "npm run build", "pip install -r server/requirements.txt"]

[start]
cmd = "echo 'Starting Flask...' && python3 server/app.py"